/**
 * @fileoverview Apply music to clips based on music-timeline.json
 * 
 * This command reads the music timeline mapping generated by the Music Editor
 * and applies the corresponding music segments to each clip.
 * 
 * Usage:
 * node src/cli/index.js apply-music --mapping ./output/music-timeline.json
 */

import fs from 'fs';
import path from 'path';
import { spawn } from 'child_process';
import { MUSIC } from '../../config.js';

/**
 * Get duration of a media file using ffprobe
 */
async function getMediaDuration(filePath) {
  return new Promise((resolve, reject) => {
    const args = [
      '-v', 'error',
      '-show_entries', 'format=duration',
      '-of', 'json',
      filePath
    ];

    const ffprobe = spawn('ffprobe', args);
    let stdout = '';
    let stderr = '';

    ffprobe.stdout.on('data', (data) => {
      stdout += data.toString();
    });

    ffprobe.stderr.on('data', (data) => {
      stderr += data.toString();
    });

    ffprobe.on('close', (code) => {
      if (code !== 0) {
        reject(new Error(`ffprobe failed: ${stderr}`));
        return;
      }

      try {
        const result = JSON.parse(stdout);
        const duration = parseFloat(result.format?.duration || 0);
        resolve(duration);
      } catch (e) {
        reject(new Error(`Failed to parse ffprobe output: ${e.message}`));
      }
    });

    ffprobe.on('error', (err) => {
      reject(new Error(`Failed to run ffprobe: ${err.message}`));
    });
  });
}

/**
 * Check if video has audio stream
 */
async function checkVideoHasAudio(filePath) {
  return new Promise((resolve) => {
    const args = [
      '-v', 'error',
      '-select_streams', 'a',
      '-show_entries', 'stream=codec_type',
      '-of', 'json',
      filePath
    ];

    const ffprobe = spawn('ffprobe', args);
    let stdout = '';

    ffprobe.stdout.on('data', (data) => {
      stdout += data.toString();
    });

    ffprobe.on('close', () => {
      try {
        const result = JSON.parse(stdout);
        resolve(result.streams && result.streams.length > 0);
      } catch (e) {
        resolve(false);
      }
    });

    ffprobe.on('error', () => {
      resolve(false);
    });
  });
}

/**
 * Find which music track contains a given time position
 */
function findMusicTrackForTime(musicTracks, timePosition) {
  let offset = 0;
  
  for (let i = 0; i < musicTracks.length; i++) {
    const track = musicTracks[i];
    const trackEnd = offset + track.duration;
    
    if (timePosition >= offset && timePosition < trackEnd) {
      return {
        track,
        trackIndex: i,
        localTime: timePosition - offset,
        offset,
      };
    }
    
    offset = trackEnd;
  }
  
  // If past all tracks, return last track
  if (musicTracks.length > 0) {
    const lastTrack = musicTracks[musicTracks.length - 1];
    const lastOffset = offset - lastTrack.duration;
    return {
      track: lastTrack,
      trackIndex: musicTracks.length - 1,
      localTime: lastTrack.duration, // End of track
      offset: lastOffset,
    };
  }
  
  return null;
}

/**
 * Apply music segment to a video clip using FFmpeg
 */
async function applyMusicToClip(options) {
  const {
    inputPath,
    outputPath,
    musicPath,
    musicStartTime,
    videoDuration,
    musicVolume = 0.7,
    gameVolume = 1.0,
    fadeDuration = 2,
  } = options;

  const hasAudio = await checkVideoHasAudio(inputPath);
  const fadeOutStart = Math.max(0, videoDuration - fadeDuration);

  return new Promise((resolve, reject) => {
    let filterComplex;
    
    if (hasAudio) {
      // Mix game audio with music
      filterComplex =
        `[0:a]volume=${gameVolume}[game];` +
        `[1:a]volume=${musicVolume},afade=t=in:st=0:d=${fadeDuration},afade=t=out:st=${fadeOutStart}:d=${fadeDuration}[music];` +
        `[game][music]amix=inputs=2:duration=first:dropout_transition=2[aout]`;
    } else {
      // No game audio - just use music with fade
      filterComplex =
        `[1:a]volume=${musicVolume},afade=t=in:st=0:d=${fadeDuration},afade=t=out:st=${fadeOutStart}:d=${fadeDuration}[aout]`;
    }

    const args = [
      '-i', inputPath,
      '-ss', String(musicStartTime),
      '-t', String(videoDuration),
      '-i', musicPath,
      '-filter_complex', filterComplex,
      '-map', '0:v',
      '-map', '[aout]',
      '-c:v', 'copy',
      '-c:a', 'aac',
      '-b:a', '192k',
      '-y',
      outputPath,
    ];

    const ffmpeg = spawn('ffmpeg', args);

    let errorOutput = '';
    ffmpeg.stderr.on('data', (data) => {
      errorOutput += data.toString();
    });

    ffmpeg.on('close', (code) => {
      if (code === 0) {
        resolve(outputPath);
      } else {
        reject(new Error(`FFmpeg failed: ${errorOutput.slice(-500)}`));
      }
    });

    ffmpeg.on('error', (err) => {
      reject(new Error(`Failed to run FFmpeg: ${err.message}`));
    });
  });
}

/**
 * Main command handler
 */
export async function applyMusicCommand(options) {
  const {
    mapping: mappingPath,
    clips: clipsOverride,
    output: outputFolder,
    musicVolume = MUSIC.defaultVolume,
    gameVolume = MUSIC.gameVolume,
    fadeDuration = MUSIC.fadeDuration,
    force = false,
  } = options;

  console.log('=== Apply Music from Timeline ===\n');

  // Load mapping file
  const resolvedMapping = path.resolve(mappingPath);
  if (!fs.existsSync(resolvedMapping)) {
    console.error(`Error: Mapping file not found: ${resolvedMapping}`);
    process.exit(1);
  }

  let timeline;
  try {
    const content = fs.readFileSync(resolvedMapping, 'utf8');
    timeline = JSON.parse(content);
  } catch (e) {
    console.error(`Error: Failed to parse mapping file: ${e.message}`);
    process.exit(1);
  }

  if (timeline.version !== 1) {
    console.error(`Error: Unsupported timeline version: ${timeline.version}`);
    process.exit(1);
  }

  // Determine clips folder
  const clipsFolder = clipsOverride || timeline.clipsFolder;
  if (!clipsFolder) {
    console.error('Error: No clips folder specified in timeline or options');
    process.exit(1);
  }

  if (!fs.existsSync(clipsFolder)) {
    console.error(`Error: Clips folder not found: ${clipsFolder}`);
    process.exit(1);
  }

  // Determine output folder
  const outputDir = outputFolder || path.join(path.dirname(clipsFolder), 'clips_with_music');
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Check music tracks
  if (!timeline.music || timeline.music.length === 0) {
    console.error('Error: No music tracks in timeline');
    process.exit(1);
  }

  // Verify music files exist
  for (const track of timeline.music) {
    if (!fs.existsSync(track.path)) {
      console.error(`Error: Music file not found: ${track.path}`);
      process.exit(1);
    }
  }

  console.log(`Clips folder: ${clipsFolder}`);
  console.log(`Output folder: ${outputDir}`);
  console.log(`Music tracks: ${timeline.music.length}`);
  console.log(`Clips to process: ${timeline.clips.length}`);
  console.log(`Music volume: ${(musicVolume * 100).toFixed(0)}%`);
  console.log(`Game volume: ${(gameVolume * 100).toFixed(0)}%`);
  console.log(`Fade duration: ${fadeDuration}s`);
  console.log('');

  // Process each clip
  let processed = 0;
  let skipped = 0;
  let errors = 0;

  for (let i = 0; i < timeline.clips.length; i++) {
    const clip = timeline.clips[i];
    const inputPath = path.join(clipsFolder, clip.filename);
    const outputPath = path.join(outputDir, clip.filename);

    console.log(`[${i + 1}/${timeline.clips.length}] ${clip.filename}`);

    // Check if already processed
    if (!force && fs.existsSync(outputPath)) {
      console.log('  Skipped (already exists)');
      skipped++;
      continue;
    }

    // Check input file exists
    if (!fs.existsSync(inputPath)) {
      console.error(`  Error: Input file not found`);
      errors++;
      continue;
    }

    // Find music track for this clip's music start time
    const musicInfo = findMusicTrackForTime(timeline.music, clip.musicStart);
    if (!musicInfo) {
      console.error(`  Error: Could not find music track for time ${clip.musicStart}`);
      errors++;
      continue;
    }

    try {
      // Get actual video duration (in case it differs from timeline)
      const videoDuration = await getMediaDuration(inputPath);

      console.log(`  Music: ${musicInfo.track.filename} @ ${musicInfo.localTime.toFixed(1)}s`);
      console.log(`  Duration: ${videoDuration.toFixed(1)}s`);

      await applyMusicToClip({
        inputPath,
        outputPath,
        musicPath: musicInfo.track.path,
        musicStartTime: musicInfo.localTime,
        videoDuration,
        musicVolume,
        gameVolume,
        fadeDuration,
      });

      console.log('  Done');
      processed++;
    } catch (e) {
      console.error(`  Error: ${e.message}`);
      errors++;
    }
  }

  console.log('\n=== Summary ===');
  console.log(`Processed: ${processed}`);
  console.log(`Skipped: ${skipped}`);
  console.log(`Errors: ${errors}`);
  console.log(`Output: ${outputDir}`);
}
