const halfWidth = { xs: 12, md: 6 };
const thirdWidth = { xs: 12, md: 4 };

export const CONFIG_SECTIONS = [
  {
    id: 'paths',
    title: 'Paths',
    fields: [
      {
        name: 'demos',
        label: 'Demos Folder',
        type: 'folder',
        grid: halfWidth,
        defaultValue: '',
      },
      {
        name: 'output',
        label: 'Output Folder',
        type: 'folder',
        grid: halfWidth,
        defaultValue: '',
      },
      {
        name: 'hlae',
        label: 'HLAE Executable',
        type: 'file',
        grid: halfWidth,
        defaultValue: '',
      },
      {
        name: 'csgo',
        label: 'CS:GO Folder',
        type: 'folder',
        grid: halfWidth,
        defaultValue: '',
      },
    ],
  },
  {
    id: 'detection',
    title: 'Detection',
    fields: [
      {
        name: 'maxDelay',
        label: 'Max Delay Between Kills (s)',
        type: 'number',
        numberType: 'int',
        defaultValue: 15,
        grid: thirdWidth,
        helperText: 'Maximum seconds between kills for a series',
      },
      {
        name: 'minSeriesKills',
        label: 'Min Series Kills',
        type: 'number',
        numberType: 'int',
        defaultValue: 3,
        grid: thirdWidth,
        helperText: 'Minimum kills for a kill series',
      },
      {
        name: 'minEnemies',
        label: 'Min Clutch Enemies',
        type: 'number',
        numberType: 'int',
        defaultValue: 2,
        grid: thirdWidth,
        helperText: 'Minimum enemies for clutch detection',
      },
    ],
  },
  {
    id: 'padding',
    title: 'Padding',
    fields: [
      {
        name: 'before',
        label: 'Padding Before (s)',
        type: 'number',
        numberType: 'int',
        defaultValue: 4,
        grid: halfWidth,
        helperText: 'Seconds before highlight starts',
      },
      {
        name: 'after',
        label: 'Padding After (s)',
        type: 'number',
        numberType: 'int',
        defaultValue: 5,
        grid: halfWidth,
        helperText: 'Seconds after highlight ends',
      },
    ],
  },
  {
    id: 'speedup',
    title: 'Speedup',
    fields: [
      {
        name: 'startDelay',
        label: 'Start Delay (s)',
        type: 'number',
        numberType: 'int',
        defaultValue: 2,
        grid: thirdWidth,
        helperText: 'Delay before first speedup',
      },
      {
        name: 'bufferAroundKills',
        label: 'Buffer Around Kills (s)',
        type: 'number',
        numberType: 'int',
        defaultValue: 2,
        grid: thirdWidth,
        helperText: 'Normal speed buffer around action',
      },
      {
        name: 'minGapDuration',
        label: 'Min Gap Duration (s)',
        type: 'number',
        numberType: 'int',
        defaultValue: 4,
        grid: thirdWidth,
        helperText: 'Minimum gap to apply speedup',
      },
    ],
  },
  {
    id: 'slowmo',
    title: 'Slow Motion',
    fields: [
      {
        name: 'duration',
        label: 'Duration (s)',
        type: 'number',
        numberType: 'float',
        defaultValue: 1,
        grid: halfWidth,
        inputProps: { step: 0.1 },
        helperText: 'Slowmo effect duration',
      },
      {
        name: 'factor',
        label: 'Slowmo Factor',
        type: 'number',
        numberType: 'float',
        defaultValue: 0.6,
        grid: halfWidth,
        inputProps: { step: 0.1, min: 0.1, max: 1 },
        helperText: 'Speed factor (0.6 = 60% speed)',
      },
    ],
  },
  {
    id: 'postprocess',
    title: 'Postprocess',
    fields: [
      {
        name: 'speedupMultiplier',
        label: 'Speedup Multiplier',
        type: 'number',
        numberType: 'int',
        defaultValue: 3,
        grid: halfWidth,
        helperText: 'Speed multiplier for gaps',
      },
      {
        name: 'showOverlay',
        label: 'Show Overlay (player name, highlight type)',
        type: 'checkbox',
        defaultValue: true,
        grid: halfWidth,
      },
    ],
  },
];
